---
- name: Install packages
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Make sure bash history records and displays timestamps by default
  # Tested on Red Hat + Ubuntu
  copy:
    dest: /etc/profile.d/acromedia.bash-history-timestamps.sh
    force: true
    backup: false
    owner: root
    group: root
    mode: 0644
    content: >
      HISTTIMEFORMAT="%Y-%m-%dT%H:%M:%S%z "
  when: set_bash_history_timestamps == true
