---
- name: Check whether packages are installed
  hosts: all
  become: yes

  tasks:

    - name: Verify utilities are available
      command: >
        {{ item }}
        with_items:
      with_items:
        - git --version
        - curl --version
        - htop --version
        - iotop --version
        - make --version
        - ncdu -v
        - nload --help
        - pv --version
        - tree --version
        - unzip --help
        - bc --version
        - screen -d -m true


    - name: Verify multitail is installed
      package_facts:
        manager: "auto"

    - name: "multitail test result"
      debug:
        msg: "multitail found"
      when: "'multitail' in ansible_facts.packages"


