---
- name: Check whether packages are installed
  hosts: all
  become: yes

  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - git
        - curl
        - mcrypt
        - htop
        - iotop
        - make
        - multitail
        - ncdu
        - nload
        - nmon
        - pv
        - tree
        - unzip
        - bc
        - screen
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Verify Packages
      assert:
        that: "'{{ item }}' in ansible_facts.packages"
      with_items:
        - git
        - curl
        - mcrypt
        - htop
        - iotop
        - make
        - multitail
        - ncdu
        - nload
        - nmon
        - pv
        - tree
        - unzip
        - bc
        - screen
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'


